baseurl = "https://jonnyflix.netlify.com/"
languageCode = "en-us"
title = "Jonas' Data Science Blog"
# Define how many pages appear per site
paginate = 10
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command

[params]
    site_author = "Jonas Weller"
    site_description = "The awesome blog of John Doe."
    location = "Mercyhurst"
    # Link custom assets relative to /static
    avatar = "img/Profil.jpg"
    header_background = "img/Background.jpg"
    header_title = "Jonas' Data Science Blog"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = "https://www.linkedin.com/in/jonasweller/"
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "jonnyflix"
    gplus     = ""
